import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service — TravelOS',
};

export default function TermsPage() {
  return (
    <main
      className="min-h-screen px-6 py-16"
      style={{ backgroundColor: '#091f36', color: 'rgba(255,255,255,0.80)' }}
    >
      <div className="max-w-2xl mx-auto">
        <Link
          href="/auth"
          className="inline-flex items-center gap-2 text-sm mb-10 transition-colors"
          style={{ color: 'rgba(255,255,255,0.40)' }}
        >
          ← Back
        </Link>

        <h1 className="text-3xl font-black text-white mb-2 tracking-tight">Terms of Service</h1>
        <p className="text-sm mb-10" style={{ color: 'rgba(255,255,255,0.35)' }}>
          Last updated: May 2026
        </p>

        <div className="space-y-8 text-sm leading-relaxed" style={{ color: 'rgba(255,255,255,0.65)' }}>
          <section>
            <h2 className="text-base font-bold text-white mb-2">1. Acceptance of Terms</h2>
            <p>
              By accessing or using TravelOS, you agree to be bound by these Terms of Service. If you
              do not agree, please do not use the service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-2">2. Description of Service</h2>
            <p>
              TravelOS is an AI-powered travel planning platform that generates personalized
              itineraries based on your preferences. The generated content is for informational
              purposes only and does not constitute professional travel advice.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-2">3. User Accounts</h2>
            <p>
              You are responsible for maintaining the confidentiality of your account credentials and
              for all activity that occurs under your account. You must be at least 13 years of age to
              use TravelOS.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-2">4. Acceptable Use</h2>
            <p>
              You agree not to misuse the service, attempt to gain unauthorized access, or use it for
              any unlawful purpose. We reserve the right to suspend or terminate accounts that violate
              these terms.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-2">5. AI-Generated Content</h2>
            <p>
              Itineraries are generated by artificial intelligence and may contain inaccuracies.
              Always verify opening hours, prices, and availability before traveling. TravelOS is not
              liable for errors in AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-2">6. Intellectual Property</h2>
            <p>
              The TravelOS name, logo, and interface design are the property of TravelOS. Your
              generated itineraries are yours to use for personal, non-commercial purposes.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-2">7. Limitation of Liability</h2>
            <p>
              TravelOS is provided "as is" without warranty of any kind. We are not responsible for
              any travel-related losses, damages, or expenses arising from the use of our service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-2">8. Changes to Terms</h2>
            <p>
              We may update these terms from time to time. Continued use of TravelOS after changes
              constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-2">9. Contact</h2>
            <p>
              For questions about these terms, please contact us at{' '}
              <a
                href="mailto:support@travelos.app"
                className="underline underline-offset-2"
                style={{ color: '#9e363a' }}
              >
                support@travelos.app
              </a>.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
